name = "NetworkEpistemology"
uuid = "fcbdc98d-c58b-4fa7-a43f-45174aa607a6"
authors = ["Jack Beasley <jack.beasley@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphIO = "aa1b3936-2fda-51b9-ab35-c553d3a640a2"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
