name = "NetworkEpistemology"
uuid = "fcbdc98d-c58b-4fa7-a43f-45174aa607a6"
authors = ["Jack Beasley <jack.beasley@gmail.com>"]
version = "0.2.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GraphIO = "aa1b3936-2fda-51b9-ab35-c553d3a640a2"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"
